const mongoose = require('mongoose');

const ReportSchema = new mongoose.Schema({
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  integrationlinks_id: { type: mongoose.Schema.Types.ObjectId, ref: 'IntegrationLink', required: true },
  Report_id: { type: String, required: true },

  realizationreport_id: Number,
  barcode: String,
  date_from: String,
  date_to: String,
  create_dt: String,
  currency_name: String,
  subject_name: String,
  nm_id: Number,
  brand_name: String,
  sa_name: String,
  ts_name: String,
  doc_type_name: String,
  quantity: Number,
  retail_price: Number,
  retail_amount: Number,
  sale_percent: Number,
  commission_percent: Number,
  office_name: String,
  supplier_oper_name: String,
  order_dt: String,
  sale_dt: String,
  rr_dt: String,
  shk_id: Number,
  retail_price_withdisc_rub: Number,
  delivery_amount: Number,
  return_amount: Number,
  delivery_rub: Number,
  gi_box_type_name: String,
  product_discount_for_report: Number,
  supplier_promo: Number,
  rid: Number,
  ppvz_spp_prc: Number,
  ppvz_kvw_prc_base: Number,
  ppvz_kvw_prc: Number,
  sup_rating_prc_up: Number,
  is_kgvp_v2: Number,
  ppvz_sales_commission: Number,
  ppvz_for_pay: Number,
  ppvz_reward: Number,
  acquiring_fee: Number,
  acquiring_percent: Number,
  acquiring_bank: String,
  ppvz_vw: Number,
  ppvz_vw_nds: Number,
  bonus_type_name: String,
  sticker_id: String,
  penalty: Number,
  additional_payment: Number,
  rebill_logistic_cost: Number,
  storage_fee: Number,
  deduction: Number,
  acceptance: Number,
  srid: String,
  report_type: Number,
  lineSum: { type: Number, default: 0 },
  exportedToMS: { type: Boolean, default: false },
  msHref: { type: String },
  msSupplyHref: { type: String },
  serviceReceiptsCreated: { type: Boolean, default: false },
  expenseOrdersCreated: { type: Boolean, default: false },
  incomeOrdersCreated: { type: Boolean, default: false },
}, { timestamps: true });

ReportSchema.index({ user: 1, integrationlinks_id: 1, Report_id: 1 });

module.exports = mongoose.model('Report', ReportSchema); 